In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
airbnb = pd.read_csv("Airbnb_NYC_2019.csv")

In [35]:
old_airbnb = pd.read_csv("Airbnb_NYC_2019.csv")

In [3]:
new_airbnb = pd.read_csv("~/Downloads/sentimentdata.csv")

In [5]:
airbnb.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'gender', 'nearest_subway_station', 'Age1', 'Age2',
       'Age3', 'Age4', 'Age5', 'Age6', 'Age7', 'Age8', 'Age9', 'Age10',
       'Decade1', 'Decade2', 'Decade3', 'Decade4', 'Decade5', 'Decade6',
       'Decade7', 'Decade8', 'Decade9', 'Decade10'],
      dtype='object')

In [6]:
new_airbnb

Unnamed: 0        id  \
0               0      2539   
1               1      2595   
2               2      3647   
3               3      3831   
4               4      5022   
...           ...       ...   
48890       48890  36484665   
48891       48891  36485057   
48892       48892  36485431   
48893       48893  36485609   
48894       48894  36487245   

                                                    name  positive  neutral  \
0                     Clean & quiet apt home by the park       2.0      6.0   
1                                  Skylit Midtown Castle       0.0      3.0   
2                    THE VILLAGE OF HARLEM....NEW YORK !       0.0      8.0   
3                        Cozy Entire Floor of Brownstone       1.0      4.0   
4       Entire Apt: Spacious Studio/Loft by central park       1.0      7.0   
...                                                  ...       ...      ...   
48890    Charming one bedroom - newly renovated rowhouse       1.0      6.0   
48891      Affordable room in Bushwick/East Williamsburg       1.0      4.0   
48892            Sunny Studio at Historical Neighborhood       0.0      5.0   
48893               43rd St. Time Square-cozy single bed       0.0      6.0   
48894  Trendy duplex in the very heart of Hell's Kitchen       1.0      8.0   

       negative   host_id      host_name neighbourhood_group  \
0           0.0      2787           John            Brooklyn   
1           0.0      2845       Jennifer           Manhattan   
2           0.0      4632      Elisabeth           Manhattan   
3           0.0      4869    LisaRoxanne            Brooklyn   
4           0.0      7192          Laura           Manhattan   
...         ...       ...            ...                 ...   
48890       0.0   8232441        Sabrina            Brooklyn   
48891       0.0   6570630        Marisol            Brooklyn   
48892       0.0  23492952  Ilgar & Aysel           Manhattan   
48893       0.0  30985759            Taz           Manhattan   
48894       1.0  68119814     Christophe           Manhattan   

            neighbourhood  latitude  longitude        room_type  price  \
0              Kensington  40.64749  -73.97237     Private room    149   
1                 Midtown  40.75362  -73.98377  Entire home/apt    225   
2                  Harlem  40.80902  -73.94190     Private room    150   
3            Clinton Hill  40.68514  -73.95976  Entire home/apt     89   
4             East Harlem  40.79851  -73.94399  Entire home/apt     80   
...                   ...       ...        ...              ...    ...   
48890  Bedford-Stuyvesant  40.67853  -73.94995     Private room     70   
48891            Bushwick  40.70184  -73.93317     Private room     40   
48892              Harlem  40.81475  -73.94867  Entire home/apt    115   
48893      Hell's Kitchen  40.75751  -73.99112      Shared room     55   
48894      Hell's Kitchen  40.76404  -73.98933     Private room     90   

       minimum_nights  number_of_reviews last_review  reviews_per_month  \
0                   1                  9  2018-10-19               0.21   
1                   1                 45  2019-05-21               0.38   
2                   3                  0         NaN                NaN   
3                   1                270  2019-07-05               4.64   
4                  10                  9  2018-11-19               0.10   
...               ...                ...         ...                ...   
48890               2                  0         NaN                NaN   
48891               4                  0         NaN                NaN   
48892              10                  0         NaN                NaN   
48893               1                  0         NaN                NaN   
48894               7                  0         NaN                NaN   

       calculated_host_listings_count  availability_365  
0                                   6               365  
1         

In [5]:
import nltk.sentiment.util as toolkit
import nltk
from nltk.corpus import opinion_lexicon
from nltk.tokenize import treebank

[nltk_data] Downloading package opinion_lexicon to
[nltk_data]     /Users/trevorcarpenter/nltk_data...
[nltk_data]   Package opinion_lexicon is already up-to-date!
[nltk_data] Downloading package treebank to
[nltk_data]     /Users/trevorcarpenter/nltk_data...
[nltk_data]   Package treebank is already up-to-date!


True

In [17]:
### first convert any emojis to their word counterpart
import demoji
demoji.download_codes()

for i, name in enumerate(airbnb['name']):
    if type(name) == str:
        emoji_map = demoji.findall(name)
        if emoji_map != {}:
            print(emoji_map)
            for key in emoji_map:
                airbnb['name'][i] = name.replace(key, str(emoji_map[key]+" "))
                print(airbnb['name'][i])

{'⭐': 'star'}


/Users/trevorcarpenter/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


Eveland the Place to Stay & Enjoy a 5-star ️ 2bdrm
{'⚡': 'high voltage'}
high voltage Quiet Gem w/roof deck on NY's Hottest Streethigh voltage 
{'❤️': 'red heart'}
UNION SQUAREred heart PENTHOUSE 2FL+TERRACEred heart EAST VIllAGE
{'♥️': 'heart suit'}
Garden Oasis in the heart suit  of NYC | Steps to Times Sq!
{'❤️': 'red heart'}
red heart  of Williamsburg, Private Entrance
{'♥': 'heart suit'}
FULLY Furnished Studio heart suit  Manhattan
{'❤️': 'red heart'}
red heart Feel@HOME Brooklyn Clinton Hill red heart 
{'❤': 'red heart'}
Lovely BR In The red heart  Of Flushing! Free Metro Card
{'™': 'trade mark'}
Gorgeous PermaGO HOMEStrade mark  - FiDi - Room 2/2
{'✨': 'sparkles'}
LARGE light filled loft/apt! PRIME Williamsburg.sparkles 
{'❤️': 'red heart'}
Sunny 1 Bdrm red heart  Private Bath red heart  No Cleaning Fee
{'❤': 'red heart'}
★★★★★- Lux Astoria |red heart of NYC| Near subway/Manhattan
{'❤️': 'red heart'}
red heart  2 Beds Option + Private Bath, Sunshine Bushwick
{'❤': 'red heart'}
1

sun  Beautiful & Quiet sun TIMES SQUARE sun  2 BDR Apt sun 
{'❤️': 'red heart'}
Bright cozy home close to Penn Station NYCred heart 
{'♥': 'heart suit'}
heart suit Private Master Bath | Express Train+Free Parking☆
{'♥': 'heart suit'}
heart suit Private Home Express Subway Station+Free Parking☆
{'⭐': 'star'}
star ︎star ︎PRIVATE Bathroomstar ︎star ︎2min to subway+huge living
{'✔': 'check mark'}
check mark  Home Away From Home check mark  100Mbps check mark  Transit Score 99
{'❤️': 'red heart'}
Renovated 1 BDR Apt~ Heart of Midtown Manhattan red heart 
{'✴': 'eight-pointed star'}
eight-pointed star SPACIOUS HOMEYeight-pointed star  2 BD Sleeps 6! Brooklyn NY
{'❤': 'red heart'}
red heart  Bushwick / Room with SmartTV & Private bathroom
{'❤': 'red heart'}
red heart  NYC/Bushwick New Private Room Size Queen red heart 
{'❤️': 'red heart'}
Cozy Parkside Studio in the red heart  of the East Village
{'♥': 'heart suit'}
Cozy (☆) Room In Upper Manhattan  (heart suit )
{'✈': 'airplane'}
airplane  N

Cozy Studio star  Premium Location in the Village!
{'⌚': 'watch', '❤️': 'red heart'}
Beautiful place in❤️of Manhattan watch Times Square
Beautiful place inred heart of Manhattan ⌚Times Square
{'⚡': 'high voltage'}
high voltage Quiet Home in Center of Village
{'❤': 'red heart'}
Best Value red heart  Memorable Vacation in NYC
{'☯': 'yin yang', '❤️': 'red heart'}
Manhattan yin yang  Brooklyn | Best of Both❤️
Manhattan ☯ Brooklyn | Best of Bothred heart 
{'☀': 'sun'}
sun Bright & sunny townhouse | Perfect for families sun 
{'♥': 'heart suit'}
Steps to Times Square Modern Apt heart suit 
{'⚓': 'anchor'}
Best place to stay anchor anchor anchor  with friends
{'✌': 'victory hand'}
Cool palce victory hand victory hand victory hand  for 2 people
{'⚡': 'high voltage', '✈': 'airplane', '☕': 'hot beverage'}
☕ ✈Fantastic Room high voltage high voltage  ✈
☕ airplane Fantastic Room ⚡⚡ airplane 
hot beverage  ✈Fantastic Room ⚡⚡ ✈
{'✌': 'victory hand'}
Amazing West Village victory hand  Location is ♕NYC

In [18]:
### extract sentiments and punctuation information and add as features

def numPunctuation(string, punctuation = '!?*.,'):
    count = 0
    for char in punctuation:
        count += string.count(char)
    return count

def numCap(string):
    count = 0
    for char in string:
        if char.isupper():
            count += 1
    return count

def sentimentCounts(string, tokenizer):
    pos_words = 0
    neg_words = 0
    neutral_words = 0
    tokenized_sent = [word.lower() for word in tokenizer.tokenize(string)]
    for word in tokenized_sent:
        if word in opinion_lexicon.positive():
            pos_words += 1
        elif word in opinion_lexicon.negative():
            neg_words += 1
        else:
            neutral_words += 1
    return np.array([pos_words, neutral_words, neg_words])

In [66]:
from sklearn.linear_model import LinearRegression as lr

In [72]:
X = np.array([subset['positive'], subset['neutral'], subset['negative']]).transpose()
y = subset['number_of_reviews']

In [75]:
reg = lr().fit(X, y)

In [76]:
reg.score(X, y)

0.0018467690314233343

In [77]:
reg.predict(X)

array([33.5837877 , 33.9356608 , 33.4322844 , ..., 34.59054049,
       32.12252502, 35.39692347])

In [78]:
y

0          9
1         45
3        270
4          9
5         74
        ... 
36328     54
36329      2
36330     58
36331      1
36332     16
Name: number_of_reviews, Length: 30510, dtype: int64

In [79]:
from sklearn.neural_network import MLPRegressor

In [82]:
reg_nn = MLPRegressor().fit(X, y)

In [83]:
reg_nn.score(X,y)

0.0031143325789001475

In [84]:
reg_nn.predict(X)

array([33.8494654 , 35.08574593, 33.25768899, ..., 35.68716102,
       33.59342871, 33.76681735])

In [85]:
y

0          9
1         45
3        270
4          9
5         74
        ... 
36328     54
36329      2
36330     58
36331      1
36332     16
Name: number_of_reviews, Length: 30510, dtype: int64

In [98]:
airbnb[airbnb['host_id'] == 2787]

id                                               name  positive  \
0          2539                 Clean & quiet apt home by the park       2.0   
10372   7937553  Riomaggiore Room. Queen Bedroom in Bklyn Townh...       0.0   
13583  10160215                               Torre del Lago Room.       0.0   
13688  10267242  Cinque Terre Room.  Clean and Quiet Queen Bedroom       2.0   
13963  10593675  La Spezia room.  Clean, quiet and comfortable bed       3.0   
21556  17263207   Brooklyn home.  Comfort and clean. Liguria room.       1.0   

       neutral  negative  host_id host_name neighbourhood_group neighbourhood  \
0          6.0       0.0     2787      John            Brooklyn    Kensington   
10372      7.0       0.0     2787      John            Brooklyn   Bensonhurst   
13583      5.0       0.0     2787      John            Brooklyn     Gravesend   
13688      6.0       0.0     2787      John            Brooklyn     Gravesend   
13963      6.0       0.0     2787      John            Brooklyn   Bensonhurst   
21556      7.0       0.0     2787      John            Brooklyn   Bensonhurst   

       latitude  longitude     room_type  price  minimum_nights  \
0      40.64749  -73.97237  Private room    149               1   
10372  40.60951  -73.97622  Private room     99               1   
13583  40.60755  -73.97410  Private room     79               1   
13688  40.60810  -73.97541  Private room    149               1   
13963  40.60951  -73.97642   Shared room     79               1   
21556  40.60877  -73.97382  Private room     49               1   

       number_of_reviews last_review  reviews_per_month  \
0                      9  2018-10-19               0.21   
10372                 21  2018-10-27               0.50   
13583                 17  2019-06-26               0.40   
13688                 24  2019-05-11               0.64   
13963                 15  2018-09-29               0.43   
21556                 19  2019-06-08               0.70   

       calculated_host_listings_count  availability_365  
0                                   6               365  
10372                               6               153  
13583                               6               174  
13688                               6               180  
13963                               6               180  
21556                               6               360

In [19]:
pairs = []
for name in new_airbnb['name']:
    try:
        pairs.append(np.array([numCap(name), numPunctuation(name), len(name)]))
    except:
        pairs.append(np.array([0,0,0]))

In [20]:
caps = np.array(pairs).transpose()[0]
punc = np.array(pairs).transpose()[1]
lengths = np.array(pairs).transpose()[2]

In [21]:
caps

array([ 1,  3, 25, ...,  4,  3,  3])

In [22]:
punc

array([0, 0, 5, ..., 0, 1, 0])

In [23]:
lengths

array([34, 21, 35, ..., 39, 36, 49])

In [118]:
new_airbnb.insert(4, "Length", lengths)

In [37]:
airbnb.insert(2, "original_name", old_airbnb['name'])
airbnb

id                                               name  \
0          2539                 Clean & quiet apt home by the park   
1          2595                              Skylit Midtown Castle   
2          3647                THE VILLAGE OF HARLEM....NEW YORK !   
3          3831                    Cozy Entire Floor of Brownstone   
4          5022   Entire Apt: Spacious Studio/Loft by central park   
...         ...                                                ...   
48890  36484665    Charming one bedroom - newly renovated rowhouse   
48891  36485057      Affordable room in Bushwick/East Williamsburg   
48892  36485431            Sunny Studio at Historical Neighborhood   
48893  36485609               43rd St. Time Square-cozy single bed   
48894  36487245  Trendy duplex in the very heart of Hell's Kitchen   

                                           original_name  positive  neutral  \
0                     Clean & quiet apt home by the park       2.0      6.0   
1                                  Skylit Midtown Castle       0.0      3.0   
2                    THE VILLAGE OF HARLEM....NEW YORK !       0.0      8.0   
3                        Cozy Entire Floor of Brownstone       1.0      4.0   
4       Entire Apt: Spacious Studio/Loft by central park       1.0      7.0   
...                                                  ...       ...      ...   
48890    Charming one bedroom - newly renovated rowhouse       1.0      6.0   
48891      Affordable room in Bushwick/East Williamsburg       1.0      4.0   
48892            Sunny Studio at Historical Neighborhood       0.0      5.0   
48893               43rd St. Time Square-cozy single bed       0.0      6.0   
48894  Trendy duplex in the very heart of Hell's Kitchen       1.0      8.0   

       negative  punctuations  capitalizations  length   host_id  ... Decade1  \
0           0.0             0                1      34      2787  ...     40s   
1           0.0             0                3      21      2845  ...     60s   
2           0.0             5               25      35      4632  ...     40s   
3           0.0             0                4      31      4869  ...     NaN   
4           0.0             0                5      48      7192  ...     50s   
...         ...           ...              ...     ...       ...  ...     ...   
48890       0.0             0                1      47   8232441  ...     60s   
48891       0.0             0                4      45   6570630  ...     70s   
48892       0.0             0                4      39  23492952  ...     NaN   
48893       0.0             1                3      36  30985759  ...     90s   
48894       1.0             0                3      49  68119814  ...     50s   

      Decade2 Decade3  Decade4  Decade5 Decade6  Decade7  Decade8  Decade9  \
0         90s     60s      90s      50s     70s      40s      40s      40s   
1         80s     80s      70s      90s     70s      90s      80s      60s   
2         80s     70s      80s      90s     90s     100s      50s      50s   
3         NaN     NaN      NaN      NaN     NaN      NaN      NaN      NaN   
4         80s     60s      50s      60s     50s      60s      90s      80s   
...       ...     ...      ...      ...     ...      ...      ...      ...   
48890     60s     80s      90s      90s     70s      60s      90s      90s   
48891     70s     90s      80s      80s     90s      80s      80s      60s   
48892     NaN     NaN      NaN      NaN     NaN      NaN      NaN      NaN   
48893     90s     90s      90s      90s     90s      80s     100s      90s   
48894     40s     50s      50s      50s     50s      50s      50s      40s   

      Decade10  
0          50s  
1          60s  
2         100s  
3          NaN  
4          80s  
...        ...  
48890      50s  
48891      70s  
48892      NaN  
48893      90s  
48894      50s  

[48895 rows x 45 columns]

In [29]:
leng

id                                               name  negative  \
0          2539                 Clean & quiet apt home by the park       0.0   
1          2595                              Skylit Midtown Castle       0.0   
2          3647                THE VILLAGE OF HARLEM....NEW YORK !       0.0   
3          3831                    Cozy Entire Floor of Brownstone       0.0   
4          5022   Entire Apt: Spacious Studio/Loft by central park       0.0   
...         ...                                                ...       ...   
48890  36484665    Charming one bedroom - newly renovated rowhouse       0.0   
48891  36485057      Affordable room in Bushwick/East Williamsburg       0.0   
48892  36485431            Sunny Studio at Historical Neighborhood       0.0   
48893  36485609               43rd St. Time Square-cozy single bed       0.0   
48894  36487245  Trendy duplex in the very heart of Hell's Kitchen       1.0   

        host_id      host_name neighbourhood_group       neighbourhood  \
0          2787           John            Brooklyn          Kensington   
1          2845       Jennifer           Manhattan             Midtown   
2          4632      Elisabeth           Manhattan              Harlem   
3          4869    LisaRoxanne            Brooklyn        Clinton Hill   
4          7192          Laura           Manhattan         East Harlem   
...         ...            ...                 ...                 ...   
48890   8232441        Sabrina            Brooklyn  Bedford-Stuyvesant   
48891   6570630        Marisol            Brooklyn            Bushwick   
48892  23492952  Ilgar & Aysel           Manhattan              Harlem   
48893  30985759            Taz           Manhattan      Hell's Kitchen   
48894  68119814     Christophe           Manhattan      Hell's Kitchen   

       latitude  longitude        room_type  ...  Decade1  Decade2  Decade3  \
0      40.64749  -73.97237     Private room  ...      40s      90s      60s   
1      40.75362  -73.98377  Entire home/apt  ...      60s      80s      80s   
2      40.80902  -73.94190     Private room  ...      40s      80s      70s   
3      40.68514  -73.95976  Entire home/apt  ...      NaN      NaN      NaN   
4      40.79851  -73.94399  Entire home/apt  ...      50s      80s      60s   
...         ...        ...              ...  ...      ...      ...      ...   
48890  40.67853  -73.94995     Private room  ...      60s      60s      80s   
48891  40.70184  -73.93317     Private room  ...      70s      70s      90s   
48892  40.81475  -73.94867  Entire home/apt  ...      NaN      NaN      NaN   
48893  40.75751  -73.99112      Shared room  ...      90s      90s      90s   
48894  40.76404  -73.98933     Private room  ...      50s      40s      50s   

      Decade4  Decade5  Decade6  Decade7 Decade8  Decade9  Decade10  
0         90s      50s      70s      40s     40s      40s       50s  
1         70s      90s      70s      90s     80s      60s       60s  
2         80s      90s      90s     100s     50s      50s      100s  
3         NaN      NaN      NaN      NaN     NaN      NaN       NaN  
4         50s      60s      50s      60s     90s      80s       80s  
...       ...      ...      ...      ...     ...      ...       ...  
48890     90s      90s      70s      60s     90s      90s       50s  
48891     80s      80s      90s      80s     80s      60s       70s  
48892     NaN      NaN      NaN      NaN     NaN      NaN       NaN  
48893     90s      90s      90s      80s    100s      90s       90s  
48894     50s      50s      50s      50s     50s      40s       50s  

[48895 rows x 39 columns]

In [36]:
old_airbnb['name']

0                       Clean & quiet apt home by the park
1                                    Skylit Midtown Castle
2                      THE VILLAGE OF HARLEM....NEW YORK !
3                          Cozy Entire Floor of Brownstone
4         Entire Apt: Spacious Studio/Loft by central park
                               ...                        
48890      Charming one bedroom - newly renovated rowhouse
48891        Affordable room in Bushwick/East Williamsburg
48892              Sunny Studio at Historical Neighborhood
48893                 43rd St. Time Square-cozy single bed
48894    Trendy duplex in the very heart of Hell's Kitchen
Name: name, Length: 48895, dtype: object

In [38]:
pd.DataFrame.to_csv(airbnb, "Airbnb_NYC_2019.csv")